### ISSUE TITLE
TODO before tournament 2019 starts 

### ISSUE THREAD

**Issue by bhaak** [junethack/Junethack#53]
- [x] add notdnethack/evilhack
- [x] add generic cross-variant achievements
- [x] fix up text for cross-variant achievements on /trophies
- [x] new pictures for cross-variant achievements
- [x] update FAQ for 2019
- [ ] SpliceHack death messages
- [x] remove lowest sum
